---
apiVersion: batch/v1
kind: Job
metadata:
  name: sampleapp-st  # <APPLICATION_NAME>-st
  namespace: test
spec:
  backoffLimit: 0  # Job のリトライ回数。シナリオテストは 0 を指定
  template:
    spec:
      serviceAccountName: sampleapp-st
      containers:
      - name: sampleapp-st
        image: gcr.io/cloud-builders/kubectl
        command:
          - bash
          - /mnt/test.sh
        envFrom:
        - configMapRef:
            name: sampleapp-st
        volumeMounts:
          - mountPath: /mnt/test.sh
            name: sampleapp-st
            subPath: test.sh
      volumes:
      - name: configs
        emptyDir: {}
      - name: sampleapp-st
        configMap:
          name: sampleapp-st
      restartPolicy: Never  # Job では Pod の再起動は不要なため Never を指定
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sampleapp-st  # <APPLICATION_NAME>-st
  namespace: test
data:
  Namespace: "test"
  Ingress: "sampleapp"
  TestFQDN: "test-sampleapp.local"

  test.sh: |
    set -xue
    PROTO=http
    TARGET=$(kubectl get ingress -n $Namespace $Ingress -o go-template='{{ $ingress := index .status.loadBalancer.ingress 0 }}{{ $ingress.ip }}')
    if ! curl -k --header "HOST:$TestFQDN" $PROTO://$TARGET; then exit 1; fi

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sampleapp-st
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: sampleapp-st
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: sampleapp-st
  namespace: test

